spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "you_password"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: "you_secret_key"
  expiration: 86400000
